feat: Add experimental umount command
sylabs/sif pull request #208
Opened 2022-04-18 14:59 UTC by dtrudg

Counterpart to mount, will unmount a squashfuse mounted filesystem via fusermount.

Fixes #205

2022-04-19 17:52 UTC, tri-adam requested changes
Few suggestions, thanks @dtrudg !

2022-04-19 17:52 UTC, tri-adam commented on internal/pkg/exp/umount.go
> +func OptUmountFusermount(path string) UmountOpt {
```suggestion
// OptUmountFusermountPath sets the path to the fusermount binary.
func OptUmountFusermountPath(path string) UmountOpt {
```

2022-04-19 17:52 UTC, tri-adam commented on internal/pkg/exp/umount.go
> +func Umount(ctx context.Context, mountPath string, opts ...UmountOpt) error {
Similar to mount, we should call out `OptUmountFusermountPath` option and the default (lookup from `PATH`).

2022-04-19 18:30 UTC, dtrudg commented on pkg/siftool/umount.go
> +		Use:     "umount <mount_path>",
Makes sense. tbh I looked at what `singularity oci` had, and didn't question that :-)

2022-04-20 02:00 UTC, tri-adam requested changes
Looks great, just two more `git mv` for consistency:

- `internal/pkg/exp/umount.go` -> `internal/pkg/exp/unmount.go`
- `internal/pkg/exp/umount_test.go` -> `internal/pkg/exp/unmount_test.go`

2022-04-20 15:24 UTC, merged